context:
  name: imagededup
  version: "0.3.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # No source distribution available, see issue https://github.com/idealo/imagededup/issues/222
  url: https://github.com/idealo/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2a890cd92f884eb50b95daf7c375d56bf955c239602cece4f8fcca2aaddade7e

build:
  script: python -m pip install . -vv
  number: 1
  # windows build requires pytorch
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython >=0.29.0
  run:
    - python
    - pytorch
    - torchvision
    - pillow >=9.0
    - tqdm
    - scikit-learn
    - pywavelets
    - matplotlib-base

tests:
  - python:
      imports:
        - imagededup
      pip_check: true

about:
  homepage: https://github.com/idealo/imagededup
  summary: 'Finding duplicate images made easy!'
  description: |
    This package provides functionality to make use of hashing algorithms that are particularly good at finding exact duplicates as well as convolutional neural networks which are also adept at finding near duplicates. An evaluation framework is also provided to judge the quality of deduplication for a given dataset.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://idealo.github.io/imagededup/
  repository: https://idealo.github.io/imagededup/

extra:
  recipe-maintainers:
    - EllaBootQC
